### ISSUE TITLE
pdDocGetInfo() crash (PDF with empty properties)

### ISSUE THREAD

**Issue by gwierzchowski** [sambitdash/PDFIO.jl#25]
pdDocGetInfo() crashes when used against PDF with empty properties:
```julia
(v1.0) julia> doc = pdDocOpen(filename);
(v1.0) julia> info = pdDocGetInfo(doc)
ERROR: BoundsError: attempt to access 0-element Array{UInt8,1} at index [1:4]
Stacktrace:
 [1] throw_boundserror(::Array{UInt8,1}, ::Tuple{UnitRange{Int64}}) at ./abstractarray.jl:484
 [2] checkbounds at ./abstractarray.jl:449 [inlined]
 [3] getindex at ./array.jl:737 [inlined]
 [4] convert(::Type{String}, ::PDFIO.Cos.CosXString) at /home/grzegorz-neo/.julia/packages/PDFIO/DyeYY/src/CosObjectHelpers.jl:11
 [5] String(::PDFIO.Cos.CosXString) at /home/grzegorz-neo/.julia/packages/PDFIO/DyeYY/src/CosObjectHelpers.jl:34
 [6] pdDocGetInfo(::PDFIO.PD.PDDocImpl) at /home/grzegorz-neo/.julia/packages/PDFIO/DyeYY/src/PDDoc.jl:135
 [7] top-level scope at none:0
```
Attached affected pdf file (it is no longer available on-line).
[ALM-2009-Aug.pdf](https://github.com/sambitdash/PDFIO.jl/files/2503741/ALM-2009-Aug.pdf)

**Comment by sambitdash** [comment]
@gwierzchowski Unfortunately, PDF specification ISO-32000 does not support empty strings in DocInfo. 
https://www.adobe.com/content/dam/acom/en/devnet/pdf/PDF32000_2008.pdf

Specification text provided below:

> The optional Info entry in the trailer of a PDF file (see 7.5.5, “File Trailer”) shall hold a document information
dictionary containing metadata for the document; Table 317 shows its contents. Any entry whose value is not
known should be omitted from the dictionary rather than included with an empty string as its value.

Many PDF writers have taken exceptions to such PDF specification directives that are not ideal. Fixing for every reader may not be practical and being too tolerant can lead to unknown side effects. 

My suggestion will be to identify all these cases but throw one exception to the end of processing so that an API user can get whatever compliant information is available but throwing meaningful exception should be help identify for non-compliant behavior and take exceptions in the API user's code not `PDFIO` code as a graceful option. Hence, you may want to review the PRs again  in these lines. If you have an alternate viewpoint or have seen a newer version of specification please let me know.

**Comment by sambitdash** [comment]
Leveling as enhancement as the error thrown is not clean and once error is throw no easy way to recover valid values. A good API should provide cleaner way to recover on genuine failures which needs to be implemented here.
